spring:
  application:
    name: mail-service
  mail:
    host: smtp.qq.com
    username: 1335799468@qq.com
    password: zvtbnuamqcamhhad11
    default-encoding: UTF-8
  # rabbitmq配置
  rabbitmq:
    host: 192.168.80.12
    username: root
    password: 123456
    virtual-host: /test